#include "circe_copy.h"

#include <stddef.h>

typedef struct {
    circe_pattern_key_t key;
    const char *name;
    const char *text;
} circe_copy_row_t;

static const circe_copy_row_t s_copy[] = {
    {CIRCE_PATTERN_GREET_FIRST_TODAY, "greet.first_today", "Welcome back."},
    {CIRCE_PATTERN_HOME_HEADING, "home.heading", "Welcome back."},
    {CIRCE_PATTERN_HOME_PROMPT, "home.prompt", "Ready to check in?"},
    {CIRCE_PATTERN_HOME_SUBLINE, "home.subline", "Start with the body."},
    {CIRCE_PATTERN_HOME_READY, "home.ready", "Ready"},
    {CIRCE_PATTERN_READY_PROMPT, "ready.prompt", "Ready when you are."},
    {CIRCE_PATTERN_READY_BODY, "ready.body", "Start with the body."},
    {CIRCE_PATTERN_BODY_INVITE, "body.invite", "Would it help to start with your body?"},
    {CIRCE_PATTERN_BODY_UNKNOWN_OKAY, "body.unknown_okay", "Not knowing is allowed. Start with what you notice."},
    {CIRCE_PATTERN_BODY_AREA_PROMPT, "body.area_prompt", "Where is your body speaking?"},
    {CIRCE_PATTERN_BODY_SENSATION_PROMPT, "body.sensation_prompt", "What does that area feel like?"},
    {CIRCE_PATTERN_BODY_INTENSITY_PROMPT, "body.intensity_prompt", "How strong is the signal? A rough answer is enough."},
    {CIRCE_PATTERN_COLOR_OPTIONAL_PROMPT, "color.optional_prompt", "Choose the color of this moment — or skip."},
    {CIRCE_PATTERN_PRIVACY_DEFAULT_NOTICE, "privacy.default_notice", "Saved privately on this device."},
    {CIRCE_PATTERN_SAVE_CONFIRMED, "save.confirmed", "Entry ready. Save when you are."},
    {CIRCE_PATTERN_DELETE_CONFIRM, "delete.confirm", "Delete this entry permanently?"},
    {CIRCE_PATTERN_DELETE_DONE, "delete.done", "Deleted. It will not appear in memory."},
    {CIRCE_PATTERN_ERROR_STORAGE_MISSING, "error.storage_missing", "Storage is not ready. Check the memory card."},
    {CIRCE_PATTERN_ERROR_SAVE_FAILED, "error.save_failed", "Could not save. Try again when ready."},
    {CIRCE_PATTERN_QUICK_ONE_TAP, "quick.one_tap", "Take a quick note."},
    {CIRCE_PATTERN_QUICK_SAVED, "quick.saved", "Saved privately."},
    {CIRCE_PATTERN_QUICK_ADD_LATER, "quick.add_later", "You can add more later."},
    {CIRCE_PATTERN_HOME_BODY, "home.body", "Body"},
    {CIRCE_PATTERN_HOME_QUICK, "home.quick", "Quick"},
    {CIRCE_PATTERN_HOME_REVIEW, "home.review", "Review"},
    {CIRCE_PATTERN_REVIEW_EMPTY, "review.empty", "No entries recorded yet."},
    {CIRCE_PATTERN_HOME_MORE, "home.more", "More"},
    {CIRCE_PATTERN_DIAG_TITLE, "diag.title", "Storage health"},
    {CIRCE_PATTERN_BODY_ADD_ANOTHER, "body.add_another", "Add another sensation?"},
    {CIRCE_PATTERN_BODY_CONTINUE, "body.continue_save", "Continue"},
    {CIRCE_PATTERN_NAV_BACK, "nav.back", "Back"},
    {CIRCE_PATTERN_NAV_CANCEL, "nav.cancel", "Cancel"},
    {CIRCE_PATTERN_PRIVACY_STANDALONE, "privacy.standalone",
     "CIRCE is standalone-first. Entries stay on this device unless you export them."},
    {CIRCE_PATTERN_STRAND_TODAY, "strand.today", "Today"},
    {CIRCE_PATTERN_EDIT_PROMPT, "edit.prompt", "What would you like to change?"},
    {CIRCE_PATTERN_EDIT_COLOR, "edit.color", "Change color"},
    {CIRCE_PATTERN_EDIT_ADD_SENSATION, "edit.add_sensation", "Add body sensation"},
    {CIRCE_PATTERN_EDIT_SAVED, "edit.saved", "Updated and saved privately."},
    {CIRCE_PATTERN_MORE_MENU, "more.menu", "Settings & themes"},
    {CIRCE_PATTERN_MORE_APPEARANCE, "more.appearance", "Appearance"},
    {CIRCE_PATTERN_MORE_STORAGE, "more.storage", "Storage"},
    {CIRCE_PATTERN_TIME_TITLE, "time.title", "Date and time"},
    {CIRCE_PATTERN_TIME_EDIT_DATE, "time.edit_date", "Set date"},
    {CIRCE_PATTERN_TIME_EDIT_TIME, "time.edit_time", "Set time"},
    {CIRCE_PATTERN_APPEARANCE_TITLE, "appearance.title", "Appearance"},
    {CIRCE_PATTERN_APPEARANCE_PROMPT, "appearance.prompt", "Choose a calm space."},
    {CIRCE_PATTERN_APPEARANCE_APPLIED, "appearance.applied", "Theme updated."},
    {CIRCE_PATTERN_CARD_READY_TITLE, "card.ready.title", "Ready"},
    {CIRCE_PATTERN_CARD_READY_DESC, "card.ready.desc", "Start with your body."},
    {CIRCE_PATTERN_CARD_QUICK_TITLE, "card.quick.title", "Quick"},
    {CIRCE_PATTERN_CARD_QUICK_DESC, "card.quick.desc", "1–3 minute reset"},
    {CIRCE_PATTERN_CARD_REVIEW_TITLE, "card.review.title", "Review"},
    {CIRCE_PATTERN_CARD_REVIEW_DESC, "card.review.desc", "Journal & trends"},
    {CIRCE_PATTERN_CARD_MORE_TITLE, "card.more.title", "More"},
    {CIRCE_PATTERN_CARD_MORE_DESC, "card.more.desc", "Settings & themes"},
    {CIRCE_PATTERN_RING_CALM, "ring.calm", "Calm"},
    {CIRCE_PATTERN_RING_FOCUS, "ring.focus", "Focus"},
    {CIRCE_PATTERN_RING_BALANCE, "ring.balance", "Balance"},
    {CIRCE_PATTERN_RING_ENERGY, "ring.energy", "Energy"},
    {CIRCE_PATTERN_TONE_PROMPT, "tone.prompt", "Choose a word, or skip."},
    {CIRCE_PATTERN_TONE_ROUGH_OK, "tone.rough_ok", "A rough word is enough."},
    {CIRCE_PATTERN_COLOR_FIELD_HINT, "color.field_hint", "Drag to tune the color. Hex updates as you move."},
    {CIRCE_PATTERN_COLOR_PRESETS_PROMPT, "color.presets_prompt", "Preset colors are available."},
    {CIRCE_PATTERN_HOME_FEED_READY, "home.feed_ready", "Ready when you are."},
    {CIRCE_PATTERN_HOME_WHEEL_HINT, "home.wheel_hint", "Rotate select · press enter"},
    {CIRCE_PATTERN_MEMORY_MENU_PROMPT, "memory.menu_prompt", "Browse saved entries."},
    {CIRCE_PATTERN_MEMORY_BROWSE_HINT, "memory.browse_hint", "Rotate entry · press view"},
    {CIRCE_PATTERN_MEMORY_INDEX_REPAIR_1, "memory.index_repair_1", "Memory index needs repair."},
    {CIRCE_PATTERN_MEMORY_INDEX_REPAIR_2, "memory.index_repair_2", "Run diagnostics when ready."},
    {CIRCE_PATTERN_REG_SAVE_PROMPT, "reg.save_prompt", "Save this session?"},
    {CIRCE_PATTERN_REG_GROUNDING_1, "reg.grounding_1", "Grounding sequence"},
    {CIRCE_PATTERN_REG_GROUNDING_2, "reg.grounding_2", "Notice one thing you can feel"},
    {CIRCE_PATTERN_REG_GROUNDING_3, "reg.grounding_3", "Breathe when ready"},
    {CIRCE_PATTERN_REG_BREATH_1, "reg.breath_1", "Follow the pulse if useful"},
    {CIRCE_PATTERN_REG_BREATH_2, "reg.breath_2", "You can stop anytime"},
    {CIRCE_PATTERN_REG_ANCHOR_1, "reg.anchor_1", "Find one contact point"},
    {CIRCE_PATTERN_REG_ANCHOR_2, "reg.anchor_2", "Soften what can soften"},
    {CIRCE_PATTERN_STATUS_SAVING, "status.saving", "Saving..."},
    {CIRCE_PATTERN_STATUS_CHECKING, "status.checking", "Checking storage..."},
    {CIRCE_PATTERN_STATUS_PROBING, "status.probing", "Probing storage..."},
    {CIRCE_PATTERN_STATUS_LOADING_MEMORY, "status.loading_memory", "Loading memory..."},
    {CIRCE_PATTERN_STATUS_LOADING, "status.loading", "Loading..."},
    {CIRCE_PATTERN_STATUS_LOAD_FAILED, "status.load_failed", "Could not load entry."},
    {CIRCE_PATTERN_STATUS_DELETE_FAILED, "status.delete_failed", "Could not delete. Entry remains saved."},
    {CIRCE_PATTERN_REVIEW_EMPTY_SUB, "review.empty_sub", "Start with the body when ready."},
    {CIRCE_PATTERN_STORAGE_UNAVAILABLE_1, "storage.unavailable_1", "Storage unavailable"},
    {CIRCE_PATTERN_STORAGE_UNAVAILABLE_2, "storage.unavailable_2", "Check memory card"},
    {CIRCE_PATTERN_PATTERNS_LOADING, "patterns.loading", "Loading patterns..."},
    {CIRCE_PATTERN_PATTERNS_EMPTY_1, "patterns.empty_1", "Not enough memory yet"},
    {CIRCE_PATTERN_PATTERNS_EMPTY_2, "patterns.empty_2", "Check-ins will appear here"},
    {CIRCE_PATTERN_PATTERNS_NONE_1, "patterns.none_1", "No strong pattern yet"},
    {CIRCE_PATTERN_PATTERNS_NONE_2, "patterns.none_2", "Keep checking in when ready"},
    {CIRCE_PATTERN_PATTERNS_HINT, "patterns.hint", "Rotate to move through patterns"},
    {CIRCE_PATTERN_PATTERNS_OBSERVATION_SUBLINE, "patterns.observation", "This is only an observation."},
    {CIRCE_PATTERN_PATTERNS_GROUNDING_SUBLINE, "patterns.grounding", "Would grounding help?"},
    {CIRCE_PATTERN_PATTERNS_ERROR_1, "patterns.error_1", "Could not load patterns"},
    {CIRCE_PATTERN_PATTERNS_ERROR_2, "patterns.error_2", "Try diagnostics"},
    {CIRCE_PATTERN_PATTERNS_STORAGE_1, "patterns.storage_1", "Storage is unavailable"},
    {CIRCE_PATTERN_PATTERNS_STORAGE_2, "patterns.storage_2", "Check diagnostics"},
    {CIRCE_PATTERN_REG_54321_TITLE, "reg.54321_title", "5-4-3-2-1"},
    {CIRCE_PATTERN_REG_54321_STEP_1, "reg.54321_step_1", "Notice 5 things you can see."},
    {CIRCE_PATTERN_REG_54321_STEP_2, "reg.54321_step_2", "Notice 4 things you can feel."},
    {CIRCE_PATTERN_REG_54321_STEP_3, "reg.54321_step_3", "Notice 3 things you can hear."},
    {CIRCE_PATTERN_REG_54321_STEP_4, "reg.54321_step_4", "Notice 2 things you can smell."},
    {CIRCE_PATTERN_REG_54321_STEP_5, "reg.54321_step_5", "Notice 1 taste, or imagine one."},
    {CIRCE_PATTERN_REG_SENSORY_TITLE, "reg.sensory_title", "Sensory reset"},
    {CIRCE_PATTERN_REG_SENSORY_STEP_1, "reg.sensory_step_1", "Less input now."},
    {CIRCE_PATTERN_REG_SENSORY_STEP_2, "reg.sensory_step_2", "Choose one anchor."},
    {CIRCE_PATTERN_REG_SENSORY_STEP_3, "reg.sensory_step_3", "Soften the screen if needed."},
    {CIRCE_PATTERN_REG_SENSORY_STEP_4, "reg.sensory_step_4", "Notice one safe object."},
    {CIRCE_PATTERN_REG_SENSORY_STEP_5, "reg.sensory_step_5", "No words needed."},
    {CIRCE_PATTERN_REG_BILATERAL_TITLE, "reg.bilateral_title", "Bilateral tap"},
    {CIRCE_PATTERN_REG_BILATERAL_LEFT, "reg.bilateral_left", "LEFT"},
    {CIRCE_PATTERN_REG_BILATERAL_RIGHT, "reg.bilateral_right", "RIGHT"},
    {CIRCE_PATTERN_REG_SESSION_COMPLETE, "reg.session_complete", "Session complete."},
    {CIRCE_PATTERN_REG_PRESS_NEXT, "reg.press_next", "Press next · long press end"},
    {CIRCE_PATTERN_REG_LONG_END, "reg.long_end", "You can stop anytime."},
    {CIRCE_PATTERN_REG_MENU_54321, "reg.menu_54321", "5-4-3-2-1"},
    {CIRCE_PATTERN_REG_MENU_SENSORY, "reg.menu_sensory", "Sensory reset"},
    {CIRCE_PATTERN_REG_MENU_BILATERAL, "reg.menu_bilateral", "Bilateral tap"},
    {CIRCE_PATTERN_COLOR_INTEL_ONLY_YOU, "color.intel_only_you", "Only you decide what it means."},
    {CIRCE_PATTERN_COLOR_REVIEW_TRAITS, "color.review_traits", "traits"},
    {CIRCE_PATTERN_PHOTO_TITLE, "photo.title", "PHOTO MEMORY"},
    {CIRCE_PATTERN_PHOTO_OPTIONAL, "photo.optional", "optional"},
    {CIRCE_PATTERN_PHOTO_LOCAL, "photo.local", "saved locally"},
    {CIRCE_PATTERN_PHOTO_CAPTURE, "photo.capture", "CAPTURE"},
    {CIRCE_PATTERN_PHOTO_SKIP, "photo.skip", "SKIP"},
    {CIRCE_PATTERN_PHOTO_SAVED, "photo.saved", "Photo memory saved."},
    {CIRCE_PATTERN_PHOTO_FAILED, "photo.failed", "Could not save photo."},
    {CIRCE_PATTERN_PHOTO_UNAVAILABLE, "photo.unavailable", "Camera unavailable."},
    {CIRCE_PATTERN_PHOTO_ATTACHED, "photo.attached", "Photo memory saved"},
    {CIRCE_PATTERN_PHOTO_ENTRY_STILL_SAVED, "photo.entry_still_saved", "Entry is still saved."},
    {CIRCE_PATTERN_VOICE_TITLE, "voice.title", "VOICE CUES"},
    {CIRCE_PATTERN_VOICE_CUES, "voice.cues", "Soft local tones only."},
    {CIRCE_PATTERN_VOICE_OFF, "voice.off", "OFF"},
    {CIRCE_PATTERN_VOICE_SOFT, "voice.soft", "SOFT"},
    {CIRCE_PATTERN_VOICE_UNAVAILABLE, "voice.unavailable", "Audio unavailable."},
    {CIRCE_PATTERN_VOICE_ENABLED, "voice.enabled", "Voice cues on."},
    {CIRCE_PATTERN_VOICE_DISABLED, "voice.disabled", "Voice cues off."},
    {CIRCE_PATTERN_DAILY_READY, "daily.ready", "CIRCE ready."},
    {CIRCE_PATTERN_DAILY_START_BODY, "daily.start_body", "Start with the body when ready."},
    {CIRCE_PATTERN_DAILY_GOOD_MORNING, "daily.good_morning", "Good morning."},
    {CIRCE_PATTERN_DAILY_GOOD_AFTERNOON, "daily.good_afternoon", "Good afternoon."},
    {CIRCE_PATTERN_DAILY_GOOD_EVENING, "daily.good_evening", "Good evening."},
    {CIRCE_PATTERN_DAILY_GOOD_NIGHT, "daily.good_night", "Good night."},
    {CIRCE_PATTERN_DAILY_NO_ENTRY_TODAY, "daily.no_entry_today", "No entry yet today."},
    {CIRCE_PATTERN_DAILY_QUIET_ALLOWED, "daily.quiet_allowed", "Quiet records are allowed."},
    {CIRCE_PATTERN_DAILY_REGULATION_RECORDED, "daily.regulation_recorded", "Regulation recorded."},
    {CIRCE_PATTERN_DAILY_REGULATION_SUB, "daily.regulation_sub", "You returned to support today."},
    {CIRCE_PATTERN_DAILY_BODY_HEARD, "daily.body_heard", "Your body has been heard."},
    {CIRCE_PATTERN_DAILY_TIME_UNSET, "daily.time_unset", "Time is unset."},
    {CIRCE_PATTERN_DAILY_TIME_UNSET_SUB, "daily.time_unset_sub", "Memory still works locally."},
    {CIRCE_PATTERN_DAILY_MEMORY_LOADING, "daily.memory_loading", "Memory is forming."},
    {CIRCE_PATTERN_DAILY_MEMORY_UNAVAILABLE, "daily.memory_unavailable", "Memory unavailable."},
    {CIRCE_PATTERN_BODY_MAP_TITLE, "body_map.title", "BODY MAP"},
    {CIRCE_PATTERN_BODY_MAP_LOADING, "body_map.loading", "Loading body map..."},
    {CIRCE_PATTERN_BODY_MAP_EMPTY_1, "body_map.empty_1", "Not enough body memory yet."},
    {CIRCE_PATTERN_BODY_MAP_EMPTY_2, "body_map.empty_2", "Start with the body when ready."},
    {CIRCE_PATTERN_BODY_MAP_OBSERVATION, "body_map.observation", "This is only an observation."},
    {CIRCE_PATTERN_BODY_MAP_MEMORY_FORMING, "body_map.memory_forming", "Your body memory is forming."},
    {CIRCE_PATTERN_BODY_MAP_ERROR_1, "body_map.error_1", "Couldn't load body map."},
    {CIRCE_PATTERN_BODY_MAP_ERROR_2, "body_map.error_2", "Try diagnostics."},
    {CIRCE_PATTERN_BODY_MAP_STORAGE_1, "body_map.storage_1", "Memory unavailable."},
    {CIRCE_PATTERN_BODY_MAP_STORAGE_2, "body_map.storage_2", "Check diagnostics."},
};

const char *circe_copy_get(circe_pattern_key_t key)
{
    for (size_t i = 0; i < sizeof(s_copy) / sizeof(s_copy[0]); i++) {
        if (s_copy[i].key == key) {
            return s_copy[i].text;
        }
    }
    return "";
}

const char *circe_copy_key_name(circe_pattern_key_t key)
{
    for (size_t i = 0; i < sizeof(s_copy) / sizeof(s_copy[0]); i++) {
        if (s_copy[i].key == key) {
            return s_copy[i].name;
        }
    }
    return "unknown";
}
