#pragma once

typedef enum {
    CIRCE_PATTERN_GREET_FIRST_TODAY,
    CIRCE_PATTERN_BODY_INVITE,
    CIRCE_PATTERN_BODY_UNKNOWN_OKAY,
    CIRCE_PATTERN_BODY_AREA_PROMPT,
    CIRCE_PATTERN_BODY_SENSATION_PROMPT,
    CIRCE_PATTERN_BODY_INTENSITY_PROMPT,
    CIRCE_PATTERN_COLOR_OPTIONAL_PROMPT,
    CIRCE_PATTERN_PRIVACY_DEFAULT_NOTICE,
    CIRCE_PATTERN_SAVE_CONFIRMED,
    CIRCE_PATTERN_DELETE_CONFIRM,
    CIRCE_PATTERN_DELETE_DONE,
    CIRCE_PATTERN_ERROR_STORAGE_MISSING,
    CIRCE_PATTERN_ERROR_SAVE_FAILED,
    CIRCE_PATTERN_QUICK_ONE_TAP,
    CIRCE_PATTERN_QUICK_SAVED,
    CIRCE_PATTERN_QUICK_ADD_LATER,
    CIRCE_PATTERN_HOME_BODY,
    CIRCE_PATTERN_HOME_QUICK,
    CIRCE_PATTERN_HOME_REVIEW,
    CIRCE_PATTERN_HOME_MORE,
    CIRCE_PATTERN_DIAG_TITLE,
    CIRCE_PATTERN_BODY_ADD_ANOTHER,
    CIRCE_PATTERN_BODY_CONTINUE,
    CIRCE_PATTERN_NAV_BACK,
    CIRCE_PATTERN_NAV_CANCEL,
    CIRCE_PATTERN_PRIVACY_STANDALONE,
    CIRCE_PATTERN_STRAND_TODAY,
    CIRCE_PATTERN_EDIT_PROMPT,
    CIRCE_PATTERN_EDIT_COLOR,
    CIRCE_PATTERN_EDIT_ADD_SENSATION,
    CIRCE_PATTERN_EDIT_SAVED,
    CIRCE_PATTERN_COUNT
} circe_pattern_key_t;

const char *circe_copy_get(circe_pattern_key_t key);
const char *circe_copy_key_name(circe_pattern_key_t key);
